name: CI with Docker

on: [push, pull_request]

jobs:
  docker-build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and Test with Docker
        run: |
          docker build -t my-app .
          docker run --rm my-app  # Run tests inside container if your image supports it
